version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn jest
workflows:
    build-and-test:
      jobs:
        - build-and-test