version: 2.1

defaults: &defaults
  working_directory: ~/mongoose-partial-dump
  executor:
    name: node/default
    tag: 'lts'
    
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn install
      - run:
          command: yarn jest
      - run:
          command: yarn build
  deploy:
    <<: *defaults
    steps:
      - run:
          name: Authenticate npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/mongoose-partial-dump/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
              tags:
                only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
              branches:
                only: /^feature\/\.*/
            