version: 2.1

defaults: &defaults
  working_directory: ~/mongoose-partial-dump
  executor:
    name: node/default
    tag: 'lts'
    
orbs:
  node: circleci/node@4.5.1
jobs:
  install-and-test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn install
      - run:
          command: yarn jest
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: yarn build
  deploy:
    <<: *defaults
    steps:
      - run:
          name: Authenticate npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/mongoose-partial-dump/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
    build-and-test:
      jobs:
        - install-and-test
        - build:
            requires:
              - install-and-test
            filters:
              tags:
                # semver regex https://gist.github.com/jhorsman/62eeea161a13b80e39f5249281e17c39#gistcomment-2877509
                only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
              branches:
                only: /^release/.*/
        - hold-deploy:
            type: approval
            requires:
              - install-and-test
            filters:
              tags:
                # semver regex https://gist.github.com/jhorsman/62eeea161a13b80e39f5249281e17c39#gistcomment-2877509
                only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
              branches:
                only: /^release/.*/
        - deploy:
            requires:
              - hold-deploy
            filters:
              tags:
                # semver regex https://gist.github.com/jhorsman/62eeea161a13b80e39f5249281e17c39#gistcomment-2877509
                only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
              branches:
                only: /^release/.*/
            